# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: security

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '41 16 * * 0'

permissions: write-all

jobs:
  scan-trivy:
    name: sec-scan-trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TEST }}

        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TEST }}
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/devops-counsel/py-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/devops-counsel/py-app:${{ github.sha }}'
          format: 'sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,WARNING'
          output: 'trivy-docker.sarif'


  scan-anchore:
    name: sec-scan-anchore
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Scan current project
        id: codescan
        uses: anchore/scan-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.TEST }}
        with:
          path: "."
          severity-cutoff: high
          acs-report-enable: true

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TEST }}
        if: ${{ always() }}
        with:
          sarif_file: ${{ steps.codescan.outputs.sarif }}
